# Generated by Django 2.0.4 on 2018-06-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_auto_20180611_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
