# Generated by Django 2.0.4 on 2018-06-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20180601_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.TextField(max_length=30)),
                ('spectacles', models.ManyToManyField(to='reservations.Shows')),
            ],
        ),
    ]
