# Generated by Django 2.0.4 on 2018-06-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_catalogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'managed': False, 'verbose_name_plural': 'Catalogues'},
        ),
    ]
