# Generated by Django 2.0.4 on 2018-06-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20180610_1559'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogue',
            table='Catalogue',
        ),
    ]
