# Generated by Django 2.0.4 on 2018-06-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20180610_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'managed': False, 'verbose_name': 'Catalogue', 'verbose_name_plural': 'Catalogues'},
        ),
        migrations.AlterModelTable(
            name='catalogue',
            table='catalogue',
        ),
    ]
