# Generated by Django 2.0.4 on 2018-06-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20180610_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shows', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.Shows')),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogues',
            },
        ),
    ]
