# Generated by Django 2.0.4 on 2018-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='year',
            field=models.TextField(default='2017/2018', max_length=30),
        ),
    ]
