# Generated by Django 2.0.4 on 2018-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_catalog_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='shows',
        ),
        migrations.AddField(
            model_name='catalog',
            name='shows',
            field=models.ManyToManyField(to='reservations.Shows'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='year',
            field=models.CharField(default='2017/2018', max_length=30),
        ),
    ]
