# Generated by Django 2.0.4 on 2018-06-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20180610_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='shows',
        ),
        migrations.AddField(
            model_name='catalog',
            name='shows',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.Shows'),
        ),
    ]
