# Generated by Django 2.0.4 on 2018-06-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20180610_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='year',
            field=models.CharField(default='2017/2018', max_length=30, unique=True),
        ),
    ]
