# Generated by Django 2.0.4 on 2018-06-12 23:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_auto_20180612_0049'),
        ('reservations', '0011_auto_20180610_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(default=datetime.datetime(2018, 6, 13, 1, 51, 33, 273948))),
                ('nombre_place', models.IntegerField()),
                ('prix_total', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Locations')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Profil')),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Shows')),
            ],
        ),
    ]
